apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: manageiq
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    generateName: manageiq-
    labels:
      name: manageiq
      app: manageiq
  spec:
    volumes:
    - name: miq-pgdb-volume
      persistentVolumeClaim:
        claimName: miq-claim
    containers:
    - image: fbladilo/miq-docker19:darga
      imagePullPolicy: IfNotPresent
      name: manageiq
      ports:
      - containerPort: 80
        protocol: TCP
      - containerPort: 443
        protocol: TCP
      resources: {}
      volumeMounts:
        - name: miq-pgdb-volume
          mountPath: /var/opt/rh/rh-postgresql94/lib/pgsql/data
      securityContext:
        privileged: true
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: manageiq
    name: manageiq
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: manageiq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: manageiq
    name: manageiq
  spec:
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: manageiq
