apiVersion: v1
kind: Template
labels:
  template: manageiq-monolithic
metadata:
  name: manageiq-monolithic
  annotations:
    description: "ManageIQ monolithic appliance with persistent storage"
    tags: "instant-app,manageiq,miq"
    iconClass: "icon-rails"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: "Exposes and load balances ManageIQ pods"
    name: ${NAME}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: https
    tls:
      termination: passthrough
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: manageiq
    annotations:
      description: "Keeps track of changes in the ManageIQ image"
  spec:
    dockerImageRepository: docker.io/manageiq/manageiq
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: miq-pgdb-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
         storage: ${DATABASE_VOLUME_CAPACITY}
- apiVersion: v1
  kind: "DeploymentConfig"
  metadata:
    name: ${NAME}
    annotations:
      description: "Defines how to deploy the ManageIQ appliance"
  spec:
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        volumes:
        - name: miq-pgdb-volume
          persistentVolumeClaim:
            claimName: miq-pgdb-claim
        containers:
        - image: manageiq/manageiq:latest
          imagePullPolicy: IfNotPresent
          name: manageiq
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 480
            timeoutSeconds: 3
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - name: miq-pgdb-volume
            mountPath: /var/opt/rh/rh-postgresql95/lib/pgsql/data
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 200
            timeoutSeconds: 3
    replicas: 1
    selector:
      name: ${NAME}
    triggers:
      - type: "ConfigChange"
      - type: "ImageChange"
        imageChangeParams:
          automatic: false
          containerNames:
            - "manageiq"
          from:
            kind: "ImageStreamTag"
            name: "manageiq:latest"
    strategy:
      type: "Recreate"
      recreateParams:
         timeoutSeconds: 1200
parameters:
  -
    name: "NAME"
    displayName: "Name"
    required: true
    description: "The name assigned to all of the frontend objects defined in this template."
    value: manageiq
  -
    name: "APPLICATION_DOMAIN"
    displayName: "Application Hostname"
    description: "The exposed hostname that will route to the application service, if left blank a value will be defaulted."
    value: ""
  -
    name: "DATABASE_VOLUME_CAPACITY"
    displayName: "Database Volume Capacity"
    required: true
    description: "Volume space available for database."
    value: "1Gi"
